apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-minecraft-operator
  namespace: minecraft-system
  labels:
    operator: kubernetes-minecraft-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: leader-election-role
  namespace: minecraft-system
  labels:
    operator: kubernetes-minecraft-operator
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leader-election-rolebinding
  namespace: minecraft-system
  labels:
    operator: kubernetes-minecraft-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election-role
subjects:
  - kind: ServiceAccount
    name: kubernetes-minecraft-operator
    namespace: minecraft-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: minecraft-server-controller-role
  labels:
    operator: kubernetes-minecraft-operator
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - replicasets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - minecraft.jameslaverack.com
    resources:
      - minecraftservers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - minecraft.jameslaverack.com
    resources:
      - minecraftservers/finalizers
    verbs:
      - update
  - apiGroups:
      - minecraft.jameslaverack.com
    resources:
      - minecraftservers/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - podmonitors
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: minecraft-server-controller-rolebinding
  labels:
    operator: kubernetes-minecraft-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: minecraft-server-controller-role
subjects:
  - kind: ServiceAccount
    name: kubernetes-minecraft-operator
    namespace: minecraft-system
