[package]
name = "minecraft_version_api"
version = "0.1.0"
edition = "2021"

[dependencies]
url = { version = "2.3.1", features = ["serde"] }
chrono = { version = "0.4.23", features = ["serde"] }
serde = { version = "1.0.148", features = ["derive"] }
serde_json = "1.0.89"

